DROP TABLE GEEK_CENTRE_INTERET;
DROP TABLE AUDIT;
DROP TABLE GEEK;
DROP TABLE CENTRE_INTERET;


#CENTRE_INTERET
CREATE TABLE CENTRE_INTERET (
ID INT NOT NULL IDENTITY,
LIBELLE VARCHAR(50)
);

#GEEK
CREATE TABLE GEEK(
ID INT NOT NULL IDENTITY,
 NOM VARCHAR(50),
 PRENOM VARCHAR(50),
 SEXE char(1),
 EMAIL VARCHAR(50)
 );
 
#GEEK_CENTRE_INTERET 
CREATE TABLE GEEK_CENTRE_INTERET (
ID_GEEK  INT   NOT NULL ,
ID_INTERET  INT   NOT NULL ,
CONSTRAINT  pk_geek_interet primary key  (ID_GEEK,ID_INTERET) );

ALTER TABLE GEEK_CENTRE_INTERET
ADD CONSTRAINT fk_id_geek foreign key (ID_GEEK) references GEEK(ID);
ALTER TABLE GEEK_CENTRE_INTERET
ADD CONSTRAINT fk_id_interet foreign key (ID_INTERET) references CENTRE_INTERET(ID);

#AUDIT
CREATE TABLE AUDIT (
ID_GEEK INT NOT NULL ,
DATE DATE,
ADRESSE_IP VARCHAR(50) );

ALTER TABLE AUDIT
ADD CONSTRAINT fk_id_geek foreign key (ID_GEEK) references GEEK(ID);


INSERT INTO "PUBLIC"."GEEK"
( "ID", "NOM", "PRENOM", "SEXE", "EMAIL" )
VALUES (null , 'Aftis', 'Hicham', 'M', 'fiftis@gmail.com');
INSERT INTO "PUBLIC"."GEEK"
( "ID", "NOM", "PRENOM", "SEXE", "EMAIL" )
VALUES (null , 'Rachidi', 'Yacine', 'M', 'yaci@gmail.com')


INSERT INTO "PUBLIC"."CENTRE_INTERET"
( "ID", "LIBELLE" )
VALUES (null , 'VBA');
INSERT INTO "PUBLIC"."CENTRE_INTERET"
( "ID", "LIBELLE" )
VALUES (null , 'C#');
INSERT INTO "PUBLIC"."CENTRE_INTERET"
( "ID", "LIBELLE" )
VALUES (null , 'JAVA');
INSERT INTO "PUBLIC"."CENTRE_INTERET"
( "ID", "LIBELLE" )
VALUES (null , 'TDD');
INSERT INTO "PUBLIC"."CENTRE_INTERET"
( "ID", "LIBELLE" )
VALUES (null , 'JUnit');
INSERT INTO "PUBLIC"."CENTRE_INTERET"
( "ID", "LIBELLE" )
VALUES (null , 'PHP');

INSERT INTO "PUBLIC"."GEEK_CENTRE_INTERET"
( "ID_GEEK", "ID_INTERET" )
VALUES (1 ,1 )
INSERT INTO "PUBLIC"."GEEK_CENTRE_INTERET"
( "ID_GEEK", "ID_INTERET" )
VALUES (1 ,2 )
INSERT INTO "PUBLIC"."GEEK_CENTRE_INTERET"
( "ID_GEEK", "ID_INTERET" )
VALUES (1 ,3 )

